### ISSUE TITLE
Alert silencing features

### ISSUE THREAD

**Issue by enelli** [DataDog/guarddog#36]
Ignore specific false positives! General users often get alert fatigue. To avoid this and make the tool more user friendly, alert silencing should be implemented. However, don’t bake it into the command. This means don’t add more flags into a command, making it super long. Instead, find ways to bake it into the code being scanned  This means:

- [ ] Allowing specific lines to be ignored in requirements.txt through semantic comments, like Semgrep
- [ ] Allowing users to create a configuration file on their local machine that specifies a list of files that escape scanning (local scan mode)
- [ ] For potential pip install command (i.e. pysecurity pip install <package>), devise a way to override the flags given by the command. For example, if cryptography is detected by pysecurity pip install, but we want to override the malicious flag, allow a way for the user to indicate, “I have reviewed cryptography, so please don’t error out or warn me”

**Comment by maciejstromich** [comment]
I would be in fave of the local config approach where you can specify the finding, path and line number to ignore. This way you can clearly indicate which lines were reviewed and what type of find you're deciding to ignore

**Comment by AngellusMortis** [comment]
It would be great to have this for running this in CI. A thought about implementation:

`pyproject.toml`
```
[tool.guarddog]
approved_packages = [
    "pygments==2.13.0"
]
```

**Comment by christophetd** [comment]
Thanks! That's definitely a feature we need and didn't want to scope in for the MVP. I'd be in favor of something that doesn't require `poetry`.

As a first step I'd suggest a `.guarddog.yaml` file sourced from the current directory (or from `GUARDDOG_CONFIG_LOCATION` if specified) that could look like:

```
approved_packages:
  # Whitelist a specific version
  pygments:
    versions: ["2.13.0"]

  # Whitelist all versions  
  pygments:
    versions: ["*"]

  # Whitelist only for a specific rule
  pyments:
    versions: ["*"]
    rules: ["typosquatting"]
```

Thoughts? cc @d-niu @vdeturckheim
