### ISSUE TITLE
Guarddog hangs when using compatible version dependency

### ISSUE THREAD

**Issue by maciejstromich** [DataDog/guarddog#86]
requirements.txt
```
Django~=3.2
requests~=2.28
```

docker-compose.yml
```
services:
  guarddog:
    image: ghcr.io/datadog/guarddog:v0.1.2
    volumes:
      - ./:/code
```
Running the command `docker-compose run --rm guarddog verify /code/requirements.txt`                                                                    

results in a hang and an output like below

```
Version 1 for package Django doesn't exist.
Version c for package Django doesn't exist.
Version 3 for package Django doesn't exist.
Version r for package Django doesn't exist.
Version . for package Django doesn't exist.
Version 2 for package Django doesn't exist.
Version 9 for package requests doesn't exist.
Version . for package requests doesn't exist.
Version 2 for package requests doesn't exist.
```
