### ISSUE TITLE
guarddog fails to parse the whole requirements.txt after encountering package name starting with git+https:// 

### ISSUE THREAD

**Issue by maciejstromich** [DataDog/guarddog#88]
requirements.txt
```
black==22.3.0
git+https://github.com/PyCQA/bandit.git@main
cfn-lint
hypothesis
```

docker-compose.yml
```
  guarddog:
    image: ghcr.io/datadog/guarddog:v0.1.4
    volumes:
      - ./:/code
```
execution:
```
docker-compose run  guarddog verify /code/requirements.txt
Received error Parse error at "'+https:/'": Expected string_endFound 0 potentially malicious indicators scanning black version 22.3.0
```

as seen in the output anything below git+https:// is not being checked for malicious indicators. 
also upon parse error the output is broken and doesn't contain break line between string_end and Found
